language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip

git:
  depth: 3

matrix:
  allow_failures:
    - go: tip
    - go: 1.6
  fast_finish: true

before_install:
  - make install

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - make lint
  - make test

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
