language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
    - go: 1.6
  fast_finish: true

before_install:
  - make install

script:
  - make lint
  - make test

after_success:
  - travis_retry goveralls -coverprofile=cover.out -service=travis-ci
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
